export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/local/sbin:$PATH"
export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/lib/postgresql83/bin:$PATH"
export PATH="$DIR/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
